'use client'

import '../styles/globals.css'
import { Inter } from 'next/font/google'

import CssBaseline from '@mui/material/CssBaseline'
import { ThemeProvider } from '@mui/material/styles'
import { Theme } from '../styles/Theme'
import MainLayout from '../components/MainLayout'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <ThemeProvider theme={Theme}>
        <CssBaseline />
        <body className={inter.className}>
          <MainLayout>{children}</MainLayout>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
        </body>
      </ThemeProvider>
    </html>
  )
}
